routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');

Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
Route::resource('categories','CategoryController');


Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::resource('books','BookController');
Route::get('/ajax/categories/search','CategoryController@ajaxSearch');

Route::resource('pegawai','PegawaiController');
Route::get('/kartutikbiodata/template', 'KartuTikBiodataController@template')->name('kartutikbiodata.template');
Route::resource('kartutikbiodata','KartuTikBiodataController');
Route::get('/kartutiktersangka/template', 'KartuTikTersangkaController@template')->name('kartutiktersangka.template');
Route::resource('kartutiktersangka','KartuTikTersangkaController');
Route::get('/kartutikbarang/template', 'KartuTikBarangController@template')->name('kartutikbarang.template');
Route::resource('kartutikbarang','KartuTikBarangController');
Route::get('/kartutikorganisasi/template', 'KartuTikOrganisasiController@template')->name('kartutikorganisasi.template');
Route::resource('kartutikorganisasi','KartuTikOrganisasiController');

Route::resource('orders','OrderController');




app/KartuTikBiodata.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class KartuTikBiodata extends Model
{    
    use SoftDeletes;

    protected $table = 'kartutik_biodatas';

    protected $primaryKey = 'id';
}

app/Http/Controllers/KartuTikBiodataController.php
<?php

namespace App\Http\Controllers;

use App\KartuTikBiodata;
use Carbon\Carbon;
use Facade\FlareClient\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Redirect;
use Mpdf\Mpdf;
use Mpdf\Output\Destination;
use Mpdf\Config\FontVariables;
use Mpdf\Config\ConfigVariables;

class KartuTikBiodataController extends Controller
{

    public function __construct()
    {
        $this->middleware(function($request, $next){

            if(Gate::allows('manage-pegawai')) return $next($request);
          
            abort(403, 'Anda tidak memiliki cukup hak akses');
          });
    }


    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    
        if (auth()->user()->kode_satker == null){
            $kartutik = KartuTikBiodata::leftJoin('satkers','kartutik_biodatas.kode_satker','=','satkers.kode_satker')
            ->select('kartutik_biodatas.*','satkers.nama_satker as nama_satker')
            ->whereIn('kartutik_biodatas.status',[2,3])
            ->get();
        }else{
            $kartutik = KartuTikBiodata::leftJoin('satkers','kartutik_biodatas.kode_satker','=','satkers.kode_satker')
            ->select('kartutik_biodatas.*','satkers.nama_satker as nama_satker')
            ->where('kartutik_biodatas.kode_satker',auth()->user()->kode_satker)
            ->whereIn('kartutik_biodatas.status',[2,3])
            ->get();
        }

        return view('kartutik_biodatas.index',compact('kartutik'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $KartuTikBiodata = new KartuTikBiodata;
        $KartuTikBiodata->status = '1';
        $KartuTikBiodata->kode_satker = auth()->user()->kode_satker;
        $KartuTikBiodata->save();

        $kartutik = KartuTikBiodata::leftJoin('satkers','kartutik_biodatas.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_biodatas.id',$KartuTikBiodata->id)
        ->select('kartutik_biodatas.*','satkers.nama_satker as nama_satker')
        ->get();

        $kenalan = DB::table('kartutik_biodatas_kenalan')->where('id_kartutik_biodatas', $KartuTikBiodata->id)->get();
        $pendidikan = DB::table('kartutik_biodatas_pendidikans')->where('id_kartutik_biodatas', $KartuTikBiodata->id)->get();
        $anak = DB::table('kartutik_biodatas_anaks')->where('id_kartutik_biodatas', $KartuTikBiodata->id)->get();
        $saudara = DB::table('kartutik_biodatas_saudara')->where('id_kartutik_biodatas', $KartuTikBiodata->id)->get();

        return view('kartutik_biodatas.create', compact('kartutik','kenalan','pendidikan','anak','saudara'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if($request->has('save')) {
            $update = KartuTikBiodata::find($request->id);
            $update->nomor = $request->nomor;
            $update->nama_lengkap = $request->nama_lengkap;
            $update->tempat_lahir = $request->tempat_lahir;
            $update->tanggal_lahir = $request->tanggal_lahir;
            $update->jenis_kelamin = $request->jenis_kelamin;
            $update->bidang = $request->bidang;
            $update->bangsa_suku = $request->bangsa_suku;
            $update->kewarganegaraan = $request->kewarganegaraan;
            $update->alamat = $request->alamat;
            $update->pendidikan = $request->pendidikan;
            $update->pekerjaan = $request->pekerjaan;
            $update->status_pernikahan = $request->status_pernikahan;
            $update->legitimasi_perkawinan = $request->legitimasi_perkawinan;
            $update->tempat_perkawinan = $request->tempat_perkawinan;
            $update->tanggal_perkawinan = $request->tanggal_perkawinan;
            $update->biografi_pekerjaan = $request->biografi_pekerjaan;
            $update->kepartaian = $request->kepartaian;
            $update->ormas_lainnya = $request->ormas_lainnya;
            $update->nama_istri_suami = $request->nama_istri_suami;
            $update->nama_ayah_kandung = $request->nama_ayah_kandung;
            $update->nama_ibu_kandung = $request->nama_ibu_kandung;
            $update->alamat_ayah_ibu = $request->alamat_ayah_ibu;
            $update->nama_ayah_mertua = $request->nama_ayah_mertua;
            $update->nama_ibu_mertua = $request->nama_ibu_mertua;
            $update->alamat_mertua = $request->alamat_mertua;
            $update->hobi_kegemaran = $request->hobi_kegemaran;
            $update->kedudukan_dimasyarakat = $request->kedudukan_dimasyarakat;
            $update->nomor_hp = $request->nomor_hp;
            $update->status = '2';
            $foto = $request->file('foto');
            if ($foto) {
                $fileName = $foto->getClientOriginalName() ;
                $destinationPath = public_path().'/storage/foto' ;
                $foto->move($destinationPath,$fileName);
                $update->foto = $fileName;
            }
            
            $update->update();

            
            // return $request->daftar_kenalan;
            DB::table('kartutik_biodatas_kenalan')->where('id_kartutik_biodatas', $request->id)->delete();
            foreach($request->daftar_kenalan as $key => $value) {
                DB::table('kartutik_biodatas_kenalan')->insert([
                    'nama_kenalan' => $value,
                    'id_kartutik_biodatas' => $request->id,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ]);
            }

            DB::table('kartutik_biodatas_anaks')->where('id_kartutik_biodatas', $request->id)->delete();
            foreach($request->daftar_anak as $key => $value) {
                DB::table('kartutik_biodatas_anaks')->insert([
                    'nama_anak' => $value,
                    'id_kartutik_biodatas' => $request->id,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ]);
            }

            DB::table('kartutik_biodatas_pendidikans')->where('id_kartutik_biodatas', $request->id)->delete();
            foreach($request->riwayat_pendidikan as $key => $value) {
                DB::table('kartutik_biodatas_pendidikans')->insert([
                    'histori_pendidikan' => $value,
                    'id_kartutik_biodatas' => $request->id,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ]);
            }

            DB::table('kartutik_biodatas_saudara')->where('id_kartutik_biodatas', $request->id)->delete();
            foreach($request->daftar_saudara as $key => $value) {
                DB::table('kartutik_biodatas_saudara')->insert([
                    'nama_saudara' => $value,
                    'id_kartutik_biodatas' => $request->id,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ]);
            }

            DB::table('kartutik_biodatas_kenalan')->where('nama_kenalan', null)->delete();
            DB::table('kartutik_biodatas_anaks')->where('nama_anak', null)->delete();
            DB::table('kartutik_biodatas_saudara')->where('nama_saudara',null)->delete();
            DB::table('kartutik_biodatas_pendidikans')->where('histori_pendidikan', null)->delete();
            return $this->edit($request->id);

        
        }elseif($request->has('finish')){
            $update = KartuTikBiodata::find($request->id);
            $update->status = '3';
            $update->update();
            return $this->edit($request->id);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kartutik = KartuTikBiodata::leftJoin('kartutik_biodatas_anaks','kartutik_biodatas.id','=','kartutik_biodatas_anaks.id_kartutik_biodatas')
        ->leftJoin('kartutik_biodatas_kenalan','kartutik_biodatas.id','=','kartutik_biodatas_kenalan.id_kartutik_biodatas')
        ->leftJoin('kartutik_biodatas_pendidikans','kartutik_biodatas.id','=','kartutik_biodatas_pendidikans.id_kartutik_biodatas')
        ->leftJoin('kartutik_biodatas_saudara','kartutik_biodatas.id','=','kartutik_biodatas_saudara.id_kartutik_biodatas')
        ->leftJoin('satkers','kartutik_biodatas.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_biodatas.id', $id)
        ->select('kartutik_biodatas.*','kartutik_biodatas_anaks.nama_anak as nama_anak','kartutik_biodatas_kenalan.nama_kenalan as nama_kenalan','kartutik_biodatas_pendidikans.histori_pendidikan as histori_pendidikan','satkers.nama_satker as nama_satker' ,'kartutik_biodatas_saudara.nama_saudara as nama_saudara')
        ->get();

        return view('kartutik_biodatas.update', compact('kartutik'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {


        $kartutik = KartuTikBiodata::leftJoin('satkers','kartutik_biodatas.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_biodatas.id',$id)

resources/views/kartutik_biodatas/index.blade.php
@extends('layouts.global')

@section('title-page')
     Kartu TIK Biodata
@endsection

@section('starter-page')
    Kartu TIK Biodata
@endsection

@section('header')
    <link rel="stylesheet" href=" {{ asset('assets/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection
{{$var = 1}}
@section('content')
 <!-- Main content -->
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible">
                                <h6><i class="icon fa fa-ban"></i> Pesan !</h6>
                                <strong>{{ session('status') }}</strong>
                        </div> 
                     @endif
                      <a href="{{ route('kartutikbiodata.create') }}" class="btn btn-info" style="margin-bottom: 10px;">Tambah Data</a>
                        <div class="card">
                                <div class="card-header">
                                  <h3 class="card-title">Kartu TIK Biodata</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                  <div class="row">
                                  <table id="table" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Satker</th>
                                        <th>Nomor</th>
                                        <th>Nama</th>
                                        <th>Alamat</th>
                                        <th>Pendidikan</th>
                                        <th>Pekerjaan</th>
                                        <th>Status</th>
                                        <th>Bidang</th>
                                        <th>Lihat</th>
                                        <th>Hapus</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        
                                    @forelse ($kartutik as $kartutik)
                                    
                                    <tr>
                                        <td>{{$var++}}</td>
                                        <td>{{ $kartutik->nama_satker }}</td>
                                        <td>{{ $kartutik->nomor }}</td>
                                        <td>{{ ucfirst($kartutik->nama_lengkap) }}</td>
                                        <td>{{ $kartutik->alamat }}</td>
                                        <td>{{ $kartutik->pendidikan }}</td>
                                        <td>{{ $kartutik->pekerjaan }}</td>
                                        @if($kartutik->status == 2)
                                        <td><button class="btn" style="background: blue;color: white;">DRAFT</button></td>
                                        @elseif($kartutik->status == 3)
                                        <td><button class="btn" style="background: green;color: white;">FINISH</button></td>
                                        @else
                                        <td><button class="btn" style="background: red;color: white;">SALAH</button></td>
                                        @endif
                                        @if($kartutik->bidang == 1)
                                        <td><button class="btn" style="background: green;color: white;">INTEL</button></td>
                                        @elseif($kartutik->bidang == 2)
                                        <td><button class="btn" style="background: red;color: white;">PIDUM</button></td>
                                        @elseif($kartutik->bidang == 3)
                                        <td><button class="btn" style="background: pink;color: white;">PIDSUS</button></td>
                                        @else
                                        <td><button class="btn" style="background: blue;color: white;">-</button></td>
                                        @endif
                                        <td>
                                          <a href="{{ route('kartutikbiodata.edit', [$kartutik->id]) }}" class="btn btn-info"><i class="fa fa-eye"></i> Detail</a>
                                        </td>
                                        <td>
                                          <form 
                                          action="{{ route('kartutikbiodata.destroy', [$kartutik->id]) }}"
                                          onsubmit="return confirm('Hapus data permanen ?')"
                                          method="POST">
                                          @csrf
                                          <input type="hidden" name="_method" value="DELETE">
                                          <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Hapus</button>
                                              </form>
                                          </td>
                                    </tr>

                                    @empty
                                        <tr>
                                            <td colspan="5">Tidak ada data</td>
                                        </tr>
                                    @endforelse
                                    
                                    </tbody>
                                  </table>
                              
              </div>
  
            </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
@endsection


@section('footer')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
        $(function () {
          $("#table").DataTable();
        });
      </script>
@endsection