routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');

Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
Route::resource('categories','CategoryController');


Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::resource('books','BookController');
Route::get('/ajax/categories/search','CategoryController@ajaxSearch');

Route::resource('pegawai','PegawaiController');
Route::get('/kartutikbiodata/template', 'KartuTikBiodataController@template')->name('kartutikbiodata.template');
Route::resource('kartutikbiodata','KartuTikBiodataController');
Route::get('/kartutiktersangka/template', 'KartuTikTersangkaController@template')->name('kartutiktersangka.template');
Route::resource('kartutiktersangka','KartuTikTersangkaController');
Route::get('/kartutikbarang/template', 'KartuTikBarangController@template')->name('kartutikbarang.template');
Route::resource('kartutikbarang','KartuTikBarangController');
Route::get('/kartutikorganisasi/template', 'KartuTikOrganisasiController@template')->name('kartutikorganisasi.template');
Route::resource('kartutikorganisasi','KartuTikOrganisasiController');

Route::resource('orders','OrderController');




app/KartuTikOrganisasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class KartuTikOrganisasi extends Model
{    
    use SoftDeletes;

    protected $table = 'kartutik_organisasi';

    protected $primaryKey = 'id';
}

app/Http/Controllers/KartuTikOrganisasiController.php
<?php

namespace App\Http\Controllers;

use App\KartuTikBarang;
use App\KartuTikOrganisasi;
use Carbon\Carbon;
use Facade\FlareClient\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Redirect;
use Mpdf\Mpdf;
use Mpdf\Output\Destination;
use Mpdf\Config\FontVariables;
use Mpdf\Config\ConfigVariables;

class KartuTikOrganisasiController extends Controller
{

    public function __construct()
    {
        $this->middleware(function($request, $next){

            if(Gate::allows('manage-pegawai')) return $next($request);
          
            abort(403, 'Anda tidak memiliki cukup hak akses');
          });
    }


    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    
        if (auth()->user()->kode_satker == null){
            $kartutik = KartuTikOrganisasi::leftJoin('satkers','kartutik_organisasi.kode_satker','=','satkers.kode_satker')
            ->select('kartutik_organisasi.*','satkers.nama_satker as nama_satker')
            ->whereIn('kartutik_organisasi.status',[2,3])
            ->get();
        }else{
            $kartutik = KartuTikOrganisasi::leftJoin('satkers','kartutik_organisasi.kode_satker','=','satkers.kode_satker')
            ->select('kartutik_organisasi.*','satkers.nama_satker as nama_satker')
            ->where('kartutik_organisasi.kode_satker',auth()->user()->kode_satker)
            ->whereIn('kartutik_organisasi.status',[2,3])
            ->get();
        }

        return view('kartutik_organisasi.index',compact('kartutik'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $KartuTikOrganisasi = new KartuTikOrganisasi();
        $KartuTikOrganisasi->status = '1';
        $KartuTikOrganisasi->kode_satker = auth()->user()->kode_satker;
        $KartuTikOrganisasi->save();

        $kartutik = KartuTikOrganisasi::leftJoin('satkers','kartutik_organisasi.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_organisasi.id',$KartuTikOrganisasi->id)
        ->select('kartutik_organisasi.*','satkers.nama_satker as nama_satker')
        ->get();

        return view('kartutik_organisasi.create', compact('kartutik'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        if($request->has('save')) {
            $update = KartuTikOrganisasi::find($request->id);
            $update->nomor = $request->nomor;
            $update->nama_organisasi = $request->nama_organisasi;
            $update->kedudukan = $request->kedudukan;
            $update->berdiri_sejak = $request->berdiri_sejak;
            $update->akte_pendirian = $request->akte_pendirian;
            $update->domisili = $request->domisili;
            $update->nomor_telepon = $request->nomor_telepon;
            $update->website_email = $request->website_email;
            $update->jumlah_oplah = $request->jumlah_oplah;
            $update->pengurus_nama = $request->pengurus_nama;
            $update->pengurus_kedudukan = $request->pengurus_kedudukan;
            $update->pengurus_periode = $request->pengurus_periode;
            $update->pengurus_nomor = $request->pengurus_nomor;
            $update->pengurus_alamat = $request->pengurus_alamat;
            $update->ruang_lingkup_kedalam = $request->ruang_lingkup_kedalam;
            $update->ruang_lingkup_keluar = $request->ruang_lingkup_keluar;
            $update->kegiatan_organisasi = $request->kegiatan_organisasi;
            $update->status = '2';
            $update->update();

            
            return $this->edit($request->id);

        
        }elseif($request->has('finish')){
            $update = KartuTikOrganisasi::find($request->id);
            $update->status = '3';
            $update->update();
            return $this->edit($request->id);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kartutik = KartuTikOrganisasi::leftJoin('kartutik_organisasi_anaks','kartutik_organisasi.id','=','kartutik_organisasi_anaks.id_kartutik_organisasi')
        ->leftJoin('kartutik_organisasi_kenalan','kartutik_organisasi.id','=','kartutik_organisasi_kenalan.id_kartutik_organisasi')
        ->leftJoin('kartutik_organisasi_pendidikans','kartutik_organisasi.id','=','kartutik_organisasi_pendidikans.id_kartutik_organisasi')
        ->leftJoin('kartutik_organisasi_saudara','kartutik_organisasi.id','=','kartutik_organisasi_saudara.id_kartutik_organisasi')
        ->leftJoin('satkers','kartutik_organisasi.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_organisasi.id', $id)
        ->select('kartutik_organisasi.*','kartutik_organisasi_anaks.nama_anak as nama_anak','kartutik_organisasi_kenalan.nama_kenalan as nama_kenalan','kartutik_organisasi_pendidikans.histori_pendidikan as histori_pendidikan','satkers.nama_satker as nama_satker' ,'kartutik_organisasi_saudara.nama_saudara as nama_saudara')
        ->get();

        return view('kartutik_organisasi.update', compact('kartutik'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {


        $kartutik = KartuTikOrganisasi::leftJoin('satkers','kartutik_organisasi.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_organisasi.id',$id)
        ->select('kartutik_organisasi.*','satkers.nama_satker as nama_satker')
        ->get();

    

        return view('kartutik_organisasi.edit', compact('kartutik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id);
        $order->status = $request->get('status');
        $order->save();
        return redirect()->route('kartutik_organisasi.index', [$order->id])->with('status','Status Order Berhasil Di Ubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kartutik = KartuTikOrganisasi::findOrFail($id);
        $kartutik->delete();
        return Redirect::back()->with('message','Operation Successful !');
    }

    public function template(Request $request, $status, $filename = '')
    {


        $kartutik = KartuTikOrganisasi::leftJoin('satkers','kartutik_organisasi.kode_satker','=','satkers.kode_satker')
        ->where('kartutik_organisasi.id',$request->id)
        ->select('kartutik_organisasi.*','satkers.nama_satker as nama_satker')
        ->get();

        $defaultConfig = (new ConfigVariables())->getDefaults();
        $fontDirs = $defaultConfig['fontDir'];		
		$defaultFontConfig = (new FontVariables())->getDefaults();
        $fontData = $defaultFontConfig['fontdata'];
		
        $kertas = 'Folio';
        $mpdf = new Mpdf([
            'fontDir' => array_merge($fontDirs, [
                'arial-cufonfonts',
            ]),
            'fontdata' => $fontData + [
                'arial' => [
                    'R' => 'ARIAL.TTF'
                ]
            ],
            'orientation' => 'P',
            'default_font_size' => 12,
            'margin_top' => 2,
            'margin_bottom' => 0,
            'margin_left' => 10,
            'margin_right' => 10,
            'mode' => 'utf-8', 
            'format' => $kertas
        ]);

        $mpdf->WriteHTML(\View::make("kartutik_organisasi.template")->with(compact('kartutik')));
        // return view('kartutik_organisasi.template', compact('kartutik','kenalan','pendidikan','anak','saudara'));

        if (empty($filename)) {
            if (!$request->encode) {
                $filename =  'kartutik_biodata.pdf';
                $mpdf->Output($filename, 'I'); 
            }
            else {
                return base64_encode($mpdf->Output('', 'S'));
            } 
        }
        else {

            $url_upload = $this->pathStoragePangkat.'/'.$filename;
            $mpdf->Output($url_upload, 'F');
            
        }
    }
}

resources/views/kartutik_organisasi/index.blade.php
@extends('layouts.global')

@section('title-page')
     Kartu TIK Organisasi
@endsection

@section('starter-page')
    Kartu TIK Organisasi
@endsection

@section('header')
    <link rel="stylesheet" href=" {{ asset('assets/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection
{{$var = 1}}
@section('content')
 <!-- Main content -->
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible">
                                <h6><i class="icon fa fa-ban"></i> Pesan !</h6>
                                <strong>{{ session('status') }}</strong>
                        </div> 
                     @endif
                      <a href="{{ route('kartutikorganisasi.create') }}" class="btn btn-info" style="margin-bottom: 10px;">Tambah Data</a>
                        <div class="card">
                                <div class="card-header">
                                  <h3 class="card-title">Kartu TIK Organisasi</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                  <div class="row">
                                  <table id="table" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Satker</th>
                                        <th>Nama Organisasi</th>
                                        <th>Akte Pendirian</th>
                                        <th>Kedudukan/status</th>
                                        <th>Berdiri Sejak</th>
                                        <th>Domisili hukum/alamat</th>
                                        <th>Lihat</th>
                                        <th>Hapus</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        
                                    @forelse ($kartutik as $kartutik)
                                    
                                    <tr>
                                        <td>{{$var++}}</td>
                                        <td>{{ $kartutik->nama_satker }}</td>
                                        <td>{{ $kartutik->nama_organisasi }}</td>
                                        <td>{{ $kartutik->akte_pendirian }}</td>
                                        <td>{{ $kartutik->kedudukan }}</td>
                                        <td>{{ $kartutik->berdiri_sejak }}</td>
                                        <td>{{ $kartutik->domisili }}</td>
                                        @if($kartutik->status == 2)
                                        <td><button class="btn" style="background: blue;color: white;">DRAFT</button></td>
                                        @elseif($kartutik->status == 3)
                                        <td><button class="btn" style="background: green;color: white;">FINISH</button></td>
                                        @else
                                        <td><button class="btn" style="background: red;color: white;">SALAH</button></td>
                                        @endif
                                        <td>
                                          <a href="{{ route('kartutikorganisasi.edit', [$kartutik->id]) }}" class="btn btn-info"><i class="fa fa-eye"></i> Detail</a>
                                        </td>
                                        <td>
                                          <form 
                                          action="{{ route('kartutikorganisasi.destroy', [$kartutik->id]) }}"
                                          onsubmit="return confirm('Hapus data permanen ?')"
                                          method="POST">
                                          @csrf
                                          <input type="hidden" name="_method" value="DELETE">
                                          <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Hapus</button>
                                              </form>
                                          </td>
                                    </tr>

                                    @empty
                                        <tr>
                                            <td colspan="8">Tidak ada data</td>
                                        </tr>
                                    @endforelse
                                    
                                    </tbody>
                                  </table>
                              
              </div>
  
            </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
@endsection


@section('footer')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
        $(function () {
          $("#table").DataTable();
        });
      </script>
@endsection

resources/views/kartutik_organisasi/template.blade.php
<?php
function tgl_indo($tanggal){
  $bulan = array (
    1 =>   'Januari',
    'Februari',
    'Maret',
    'April',
    'Mei',
    'Juni',
    'Juli',
    'Agustus',
    'September',
    'Oktober',
    'November',
    'Desember'
  );
  $pecahkan = explode('-', $tanggal);

  if($tanggal == NULL){
      return NULL;
  }
 
  return $pecahkan[2] . ' ' . $bulan[ (int)$pecahkan[1] ] . ' ' . $pecahkan[0];
}

function bln_indo($req){
  $bulan = array (
    1 =>   'Januari',
    'Februari',
    'Maret',
    'April',
    'Mei',
    'Juni',
    'Juli',
    'Agustus',
    'September',
    'Oktober',
    'November',
    'Desember'
  );
  
 
  return $bulan[ (int)$req ];
}

function pecah_kata_depan($req){
  $kalimat = $req;
  $jumlah = "2";
  $hasil = implode(" ", array_slice(explode(" ", $kalimat), 0, $jumlah));
  return $hasil;
}

function pecah_kata_belakang($req){
  $kalimat = $req;
  $jumlah = "10";
  $hasil = implode(" ", array_slice(explode(" ", $kalimat), 2, $jumlah));
  return $hasil;
}

function hitung_umur($tanggal_lahir){
	$birthDate = new DateTime($tanggal_lahir);
	$today = new DateTime("today");
	if ($birthDate > $today) { 
	    exit("0 tahun 0 bulan 0 hari");
	}
	$y = $today->diff($birthDate)->y;
	$m = $today->diff($birthDate)->m;
	$d = $today->diff($birthDate)->d;
	return $y." tahun ".$m." bulan ".$d." hari";
}

?>

<table style="width: 100%">
  <tbody>
    <tr style="height: 1px;">
      <td class="tg-c3ow" style="height: 1px; width:2%;">&nbsp;</td>
      <td class="tg-c3ow" style="height: 1px; width:4%;">&nbsp;</td>
      <td class="tg-c3ow" style="height: 1px; width:4%;">&nbsp;</td>
      <td class="tg-c3ow" style="height: 1px; width:4%;">&nbsp;</td>
      <td class="tg-c3ow" style="height: 1px; width:27%;">&nbsp;</td>
      <td class="tg-c3ow" style="height: 1px; width:3%;">&nbsp;</td>
      <td class="tg-c3ow" style="height: 1px;">&nbsp;</td>
    </tr>
  <tr style="height: 18px;">
  <td class="tg-0pky" style="height: 18px;" colspan="6">{{pecah_kata_depan($kartutik[0]->nama_satker)}}</td>
  <th class="tg-dvpl" style="height: 18px; text-align: right;">R.IN.34</th>
  </tr>
  <tr style="height: 18px;">
  <td class="tg-0pky" style="height: 18px;" colspan="7">{{pecah_kata_belakang($kartutik[0]->nama_satker)}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-9353" style="height: 18px; text-align: center; " colspan="7"></td>
      </tr>
  <tr style="height: 18px;">
<td class="tg-9353" style="height: 18px; text-align: center; " colspan="7"><b><u>KARTU TIK ORGANISASI
</u></b>
  </tr>
  <tr style="height: 23.5px;">
  <td class="tg-c3ow "  style="height: 23.5px; text-align: center; " colspan="7">NOMOR : {{$kartutik[0]->nomor}}</td>
  </tr>
  <tr style="height: 18px;">
  <td class="tg-c3ow" style="height: 18px;" colspan="7">&nbsp;</td>
  
  </tr>
  <tr style="height: 18px;">
  <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
  <td class="tg-c3ow" style="height: 18px;">I.</td>
  <td class="tg-0pky" style="height: 18px;" colspan="5">IDENTITAS</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">1.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Nama Organisasi</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->nama_organisasi}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">2.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Akte Pendirian</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->akte_pendirian}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">3.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Kedudukan/status</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->kedudukan}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">4.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Berdiri Sejak</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->berdiri_sejak}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">5.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Domisili hukum/alamat</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->domisili}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">6.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Nomor Telpon</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->nomor_telepon}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">7.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Website/ E-mail</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->website_email}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">8.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Pengurus</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">- Nama</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->pengurus_nama}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">- Kedudukan</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->pengurus_kedudukan}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">- Periode Tahun</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->pengurus_periode}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">- Alamat</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->pengurus_alamat}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">- Nomor Telpon/ HP</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->pengurus_nomor}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">9.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Ruang lingkup kegiatan organisasi</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">a. Kedalam</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->ruang_lingkup_kedalam}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">b. Keluar</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->ruang_lingkup_keluar}}</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">10.</td>
    <td class="tg-0pky" style="height: 18px;" colspan="2" style="width:5%">Jumlah Oplah</td>
    <td class="tg-c3ow" style="height: 18px;">:</td>
    <td class="tg-0pky" style="height: 18px;">{{$kartutik[0]->jumlah_oplah}}</td>
  </tr>
  <tr style="height: 18px;">
  <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
  <td class="tg-c3ow" style="height: 18px;">II.</td>
  <td class="tg-0pky" style="height: 18px;" colspan="5">KEGIATAN ORGANISASI / PENGURUS ORGANISASI YANG BERKAITAN DENGAN PELANGARAN HUKUM</td>
  </tr>
  <tr style="height: 18px;">
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-c3ow" style="height: 18px;">&nbsp;</td>
    <td class="tg-0pky" style="height: 18px;" colspan="5">{{$kartutik[0]->kegiatan_organisasi}}</td>
  </tr>
  </tbody>
</table>
  